# Usa la misma versión de Node.js que tu API
FROM node:18-alpine 
# Establecer el directorio de trabajo
WORKDIR /app
# Copiar archivos de configuración y código
COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "test"]