apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: chipasito/api:v1  # Reemplaza con la imagen correcta de tu API
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: postgres-config
