apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: miapp
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/miapp
