name: Deploy to Render

on:
  push:
    branches:
      - main  # Se ejecutará en cada push a la rama main.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Deploy on Render
        run: |
          curl -X POST "https://dashboard.render.com/web/srv-cviqaeq4d50c73a82u20?key=${{ secrets.RENDER_API_KEY }}"